### ISSUE TITLE
Using the plugin on desktop editor

### ISSUE THREAD

**Issue by filippogambarota** [ONLYOFFICE/plugin-mendeley#10]
I'm trying to install the plugin on the desktop editor but I cannot run it. How can I do?

**Comment by Eloncase** [comment]
Hello @filippogambarota, to install plugins to desktop editors you can use [this](https://api.onlyoffice.com/plugin/installation).
However, for now mendeley plugin is not supported on desktop installation because it requires oauth authorization.

**Comment by filippogambarota** [comment]
Thanks @Eloncase for the response. So I cannot use it on my desktop installation? is there some workaround? will it be possible in future to use it regularly?

**Comment by Eloncase** [comment]
Yes, for now you cannot use it on desktop installation, and no workarounds that I know of.
At some point in future plugin will be available for desktop version.

**Comment by filippogambarota** [comment]
Thanks! I hope that it will be available in future!
