### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by Brogalang** [ONLYOFFICE/plugin-mendeley#17]
I always got This site can’t be reached when triying connect Onlyoffice with mendeley. 

The webpage at https://api.mendeley.com/oauth/v2/authorize might be temporarily down or it may have moved permanently to a new web address.
ERR_UNSAFE_REDIRECT

please help I really love this OnlyOffice

**Comment by DenisDeeSign** [comment]
@Brogalang, do you use DocumentServer or DesktopEditors?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
