### ISSUE TITLE
client authentication failed  on mendeley website

### ISSUE THREAD

**Issue by flyinskybtx** [ONLYOFFICE/plugin-mendeley#29]
I have filled the application ID, and when I login, the Mendeley site blocked me,  and reads :

"An invalid request was made by a third-party app

Client authentication failed"

**Comment by mschepers188** [comment]
I get exactly the same error.

**Comment by DenisDeeSign** [comment]
Hi @flyinskybtx and @mschepers188,
please specify what product are you using, Document Server or Desktop Editors.

**Comment by mschepers188** [comment]
My apologies, my problem is for the Desktop version. Every time I'm redirected to the browser for authentication I get the above error.

**Comment by DenisDeeSign** [comment]
Duplicate of #33
